
import { InsurancePlan } from './types';

export const SAMPLE_DATA: InsurancePlan[] = [
  {
    BusinessYear: 2026,
    StateCode: "TX",
    IssuerId: 20069,
    IssuerMarketPlaceMarketingName: "Oscar Insurance Company",
    SourceName: "HIOS",
    ImportDate: "28-10-2025",
    StandardComponentId: "20069TX0510021",
    PlanMarketingName: "Gold Simple Guided Care 20069TX051",
    HIOSProductId: "20069TX051",
    NetworkId: "TXN002",
    ServiceAreaId: "TXS002",
    FormularyId: "TXF001",
    IsNewPlan: "Existing",
    PlanId: "20069TX0510021",
    PlanVariantMarketingName: "Gold Simple Guided Care",
    PlanType: "HMO",
    MetalLevel: "Gold",
    DesignType: "Not Applicable",
    UniquePlanDesign: "No",
    QHPNonQHPTypeld: "Both",
    MaximumUnderageDependent: 3,
    DependentMaximumAgeRule: 25,
    AgeDeterminationRule: "Age on effective date",
    MedicalDentalIndicator: "Medical",
    DentalOnlyPlan: "No",
    MarketCoverage: "Individual",
    TEHBDedInnTier1Individual: "$3,300",
    TEHBDedInnTier1FamilyPerPerson: "$3,300 per person",
    TEHBDedInnTier1FamilyPerGroup: "$6,600 per group",
    TEHBDedInnTier1Coinsurance: "20.00%",
    TEHBInnTier1IndividualMOOP: "$9,950",
    TEHBInnTier1FamilyPerPersonMOOP: "$9,950 per person",
    TEHBInnTier1FamilyPerGroupMOOP: "$19,900 per group",
    CoveredBenefitCount: 192,
    BenefitCount: 67,
    NationalNetwork: "No",
    IsHSAEligible: "No",
    IsNoticeRequiredForPregnancy: "No",
    IsReferralRequiredForSpecialist: "Yes",
    SpecialistRequiringReferral: "All specialists except Behavioral Health, Obstetrics and",
    FormularyURL: "https://www.hios.gov",
    URLForEnrollmentPayment: "https://business.hioscar.com",
    PlanBrochure: "https://www.hios.gov",
    URLForSummaryofBenefitsCoverage: "https://d3ul0st9g52g6o.cloudfront.net",
    OutOfServiceAreaCoverageDescription: "Emergency and Urgent Services Only",
    OutOfCountryCoverage: "Yes",
    OutOfCountryCoverageDescription: "Emergency Services Only",
    SBCHavingBabyDeductible: "$3,300",
    SBCHavingBabyCopayment: "$500",
    SBCHavingBabyCoinsurance: "20%",
    SBCHavingBabyLimit: "$60",
    SBCHavingDiabetesDeductible: "$3,300",
    SBCHavingDiabetesCopayment: "$20",
    SBCHavingDiabetesCoinsurance: "20%",
    SBCHavingDiabetesLimit: "$20",
    SBCHavingSimplefractureDeductible: "$3,300",
    SBCHavingSimplefractureCopayment: "$300",
    SBCHavingSimplefractureCoinsurance: "20%",
    SBCHavingSimplefractureLimit: "$0"
  },
  {
    BusinessYear: 2026,
    StateCode: "TX",
    IssuerId: 20069,
    IssuerMarketPlaceMarketingName: "Oscar Insurance Company",
    SourceName: "HIOS",
    ImportDate: "28-10-2025",
    StandardComponentId: "20069TX0510022",
    PlanMarketingName: "Gold Classic Guided Care 20069TX051",
    HIOSProductId: "20069TX051",
    NetworkId: "TXN002",
    ServiceAreaId: "TXS003",
    FormularyId: "TXF001",
    IsNewPlan: "Existing",
    PlanId: "20069TX0510022",
    PlanVariantMarketingName: "Gold Classic Guided Care",
    PlanType: "HMO",
    MetalLevel: "Gold",
    DesignType: "Not Applicable",
    UniquePlanDesign: "No",
    QHPNonQHPTypeld: "Both",
    MaximumUnderageDependent: 3,
    DependentMaximumAgeRule: 25,
    AgeDeterminationRule: "Age on effective date",
    MedicalDentalIndicator: "Medical",
    DentalOnlyPlan: "No",
    MarketCoverage: "Individual",
    TEHBDedInnTier1Individual: "$2,500",
    TEHBDedInnTier1FamilyPerPerson: "$2,500 per person",
    TEHBDedInnTier1FamilyPerGroup: "$5,000 per group",
    TEHBDedInnTier1Coinsurance: "30.00%",
    TEHBInnTier1IndividualMOOP: "$8,000",
    TEHBInnTier1FamilyPerPersonMOOP: "$8,000 per person",
    TEHBInnTier1FamilyPerGroupMOOP: "$16,000 per group",
    CoveredBenefitCount: 192,
    BenefitCount: 67,
    NationalNetwork: "No",
    IsHSAEligible: "No",
    IsNoticeRequiredForPregnancy: "No",
    IsReferralRequiredForSpecialist: "Yes",
    SpecialistRequiringReferral: "All specialists except Behavioral Health, Obstetrics and",
    FormularyURL: "https://www.hios.gov",
    URLForEnrollmentPayment: "https://business.hioscar.com",
    PlanBrochure: "https://www.hios.gov",
    URLForSummaryofBenefitsCoverage: "https://d3ul0st9g52g6o.cloudfront.net",
    OutOfServiceAreaCoverageDescription: "Emergency and Urgent Services Only",
    OutOfCountryCoverage: "Yes",
    OutOfCountryCoverageDescription: "Emergency Services Only",
    SBCHavingBabyDeductible: "$2,500",
    SBCHavingBabyCopayment: "$300",
    SBCHavingBabyCoinsurance: "30%",
    SBCHavingBabyLimit: "$60",
    SBCHavingDiabetesDeductible: "$3,500",
    SBCHavingDiabetesCopayment: "$500",
    SBCHavingDiabetesCoinsurance: "30%",
    SBCHavingDiabetesLimit: "$20",
    SBCHavingSimplefractureDeductible: "$2,100",
    SBCHavingSimplefractureCopayment: "$200",
    SBCHavingSimplefractureCoinsurance: "30%",
    SBCHavingSimplefractureLimit: "$0"
  },
  {
    BusinessYear: 2026,
    StateCode: "NY",
    IssuerId: 30045,
    IssuerMarketPlaceMarketingName: "Empire BlueCross",
    SourceName: "HIOS",
    ImportDate: "15-11-2025",
    StandardComponentId: "30045NY0110005",
    PlanMarketingName: "Silver Premier EPO 30045NY011",
    HIOSProductId: "30045NY011",
    NetworkId: "NYN001",
    ServiceAreaId: "NYS001",
    FormularyId: "NYF002",
    IsNewPlan: "New",
    PlanId: "30045NY0110005",
    PlanVariantMarketingName: "Silver Premier EPO",
    PlanType: "EPO",
    MetalLevel: "Silver",
    DesignType: "Standard",
    UniquePlanDesign: "No",
    QHPNonQHPTypeld: "QHP",
    MaximumUnderageDependent: 3,
    DependentMaximumAgeRule: 26,
    AgeDeterminationRule: "Age on effective date",
    MedicalDentalIndicator: "Medical",
    DentalOnlyPlan: "No",
    MarketCoverage: "Individual",
    TEHBDedInnTier1Individual: "$4,500",
    TEHBDedInnTier1FamilyPerPerson: "$4,500 per person",
    TEHBDedInnTier1FamilyPerGroup: "$9,000 per group",
    TEHBDedInnTier1Coinsurance: "15.00%",
    TEHBInnTier1IndividualMOOP: "$9,450",
    TEHBInnTier1FamilyPerPersonMOOP: "$9,450 per person",
    TEHBInnTier1FamilyPerGroupMOOP: "$18,900 per group",
    CoveredBenefitCount: 210,
    BenefitCount: 75,
    NationalNetwork: "Yes",
    IsHSAEligible: "Yes",
    IsNoticeRequiredForPregnancy: "Yes",
    IsReferralRequiredForSpecialist: "No",
    SpecialistRequiringReferral: "None",
    FormularyURL: "https://www.empireblue.com",
    URLForEnrollmentPayment: "https://www.empireblue.com/enroll",
    PlanBrochure: "https://www.empireblue.com/brochure",
    URLForSummaryofBenefitsCoverage: "https://www.empireblue.com/sbc",
    OutOfServiceAreaCoverageDescription: "Coverage provided through national network partners",
    OutOfCountryCoverage: "No",
    OutOfCountryCoverageDescription: "No Out of Country Coverage",
    SBCHavingBabyDeductible: "$4,500",
    SBCHavingBabyCopayment: "$0",
    SBCHavingBabyCoinsurance: "15%",
    SBCHavingBabyLimit: "$60",
    SBCHavingDiabetesDeductible: "$1,200",
    SBCHavingDiabetesCopayment: "$40",
    SBCHavingDiabetesCoinsurance: "15%",
    SBCHavingDiabetesLimit: "$20",
    SBCHavingSimplefractureDeductible: "$500",
    SBCHavingSimplefractureCopayment: "$250",
    SBCHavingSimplefractureCoinsurance: "15%",
    SBCHavingSimplefractureLimit: "$20"
  },
  {
    BusinessYear: 2026,
    StateCode: "CA",
    IssuerId: 10022,
    IssuerMarketPlaceMarketingName: "Blue Shield of California",
    SourceName: "HIOS",
    ImportDate: "10-11-2025",
    StandardComponentId: "10022CA0010001",
    PlanMarketingName: "Bronze 60 PPO 10022CA001",
    HIOSProductId: "10022CA001",
    NetworkId: "CAN001",
    ServiceAreaId: "CAS001",
    FormularyId: "CAF001",
    IsNewPlan: "Existing",
    PlanId: "10022CA0010001",
    PlanVariantMarketingName: "Bronze 60 PPO",
    PlanType: "PPO",
    MetalLevel: "Bronze",
    DesignType: "Standard",
    UniquePlanDesign: "No",
    QHPNonQHPTypeld: "Both",
    MaximumUnderageDependent: 3,
    DependentMaximumAgeRule: 26,
    AgeDeterminationRule: "Age on effective date",
    MedicalDentalIndicator: "Medical",
    DentalOnlyPlan: "No",
    MarketCoverage: "Individual",
    TEHBDedInnTier1Individual: "$6,300",
    TEHBDedInnTier1FamilyPerPerson: "$6,300 per person",
    TEHBDedInnTier1FamilyPerGroup: "$12,600 per group",
    TEHBDedInnTier1Coinsurance: "40.00%",
    TEHBInnTier1IndividualMOOP: "$9,100",
    TEHBInnTier1FamilyPerPersonMOOP: "$9,100 per person",
    TEHBInnTier1FamilyPerGroupMOOP: "$18,200 per group",
    CoveredBenefitCount: 185,
    BenefitCount: 60,
    NationalNetwork: "Yes",
    IsHSAEligible: "No",
    IsNoticeRequiredForPregnancy: "No",
    IsReferralRequiredForSpecialist: "No",
    SpecialistRequiringReferral: "None",
    FormularyURL: "https://www.blueshieldca.com",
    URLForEnrollmentPayment: "https://www.blueshieldca.com/payment",
    PlanBrochure: "https://www.blueshieldca.com/brochure",
    URLForSummaryofBenefitsCoverage: "https://www.blueshieldca.com/sbc",
    OutOfServiceAreaCoverageDescription: "PPO Network coverage available nationwide",
    OutOfCountryCoverage: "Yes",
    OutOfCountryCoverageDescription: "BlueCard Worldwide Coverage",
    SBCHavingBabyDeductible: "$6,300",
    SBCHavingBabyCopayment: "$500",
    SBCHavingBabyCoinsurance: "40%",
    SBCHavingBabyLimit: "$60",
    SBCHavingDiabetesDeductible: "$6,300",
    SBCHavingDiabetesCopayment: "$150",
    SBCHavingDiabetesCoinsurance: "40%",
    SBCHavingDiabetesLimit: "$20",
    SBCHavingSimplefractureDeductible: "$6,300",
    SBCHavingSimplefractureCopayment: "$300",
    SBCHavingSimplefractureCoinsurance: "40%",
    SBCHavingSimplefractureLimit: "$0"
  }
];
